
  services:

    # =========================================================
    # POSTGRESQL
    # =========================================================

    postgres:
      image: postgres:16
      container_name: postgres
      environment:
        POSTGRES_DB: stockdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data


    # =========================================================
    # ZOOKEEPER
    # =========================================================

    zookeeper:
      image: confluentinc/cp-zookeeper:7.6.0
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000


    # =========================================================
    # KAFKA
    # =========================================================

    kafka:
      image: confluentinc/cp-kafka:7.6.0
      container_name: kafka

      depends_on:
        - zookeeper

      ports:
        - "9092:9092"

      environment:
        KAFKA_BROKER_ID: 1

        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

        KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092

        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


    # =========================================================
    # EUREKA DISCOVERY SERVER
    # =========================================================

    eureka:
      build: ../discovery-server
      container_name: discovery-server

      ports:
        - "8761:8761"


    # =========================================================
    # API GATEWAY
    # =========================================================

    gateway:
      build: ../api-gateway
      container_name: api-gateway

      ports:
        - "8080:8080"

      depends_on:
        - eureka


    # =========================================================
    # ORDER SERVICE - 3 REPLICAS
    # =========================================================

    order1:
      build: ../services/order-service
      container_name: order1

      environment:
        SERVER_PORT: 8081

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: order1

      depends_on:
        - postgres
        - kafka
        - eureka


    order2:
      build: ../services/order-service
      container_name: order2

      environment:
        SERVER_PORT: 8081

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: order2

      depends_on:
        - postgres
        - kafka
        - eureka


    order3:
      build: ../services/order-service
      container_name: order3

      environment:
        SERVER_PORT: 8081

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: order3

      depends_on:
        - postgres
        - kafka
        - eureka


    # =========================================================
    # RISK SERVICE - 3 REPLICAS
    # =========================================================

    risk1:
      build: ../services/risk-service
      container_name: risk1

      environment:
        SERVER_PORT: 8082

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: risk1

      depends_on:
        - postgres
        - kafka
        - eureka


    risk2:
      build: ../services/risk-service
      container_name: risk2

      environment:
        SERVER_PORT: 8082

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: risk2

      depends_on:
        - postgres
        - kafka
        - eureka


    risk3:
      build: ../services/risk-service
      container_name: risk3

      environment:
        SERVER_PORT: 8082

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: risk3

      depends_on:
        - postgres
        - kafka
        - eureka


    # =========================================================
    # PORTFOLIO SERVICE - 3 REPLICAS
    # =========================================================

    portfolio1:
      build: ../services/portfolio-service
      container_name: portfolio1

      environment:
        SERVER_PORT: 8083

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: portfolio1

      depends_on:
        - postgres
        - kafka
        - eureka


    portfolio2:
      build: ../services/portfolio-service
      container_name: portfolio2

      environment:
        SERVER_PORT: 8083

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: portfolio2

      depends_on:
        - postgres
        - kafka
        - eureka


    portfolio3:
      build: ../services/portfolio-service
      container_name: portfolio3

      environment:
        SERVER_PORT: 8083

        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: portfolio3

      depends_on:
        - postgres
        - kafka
        - eureka


    # =========================================================
    # NOTIFICATION SERVICE - 3 REPLICAS
    # =========================================================

    notification1:
      build: ../services/notification-service
      container_name: notification1

      environment:
        SERVER_PORT: 8084

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: notification1

      depends_on:
        - kafka
        - eureka


    notification2:
      build: ../services/notification-service
      container_name: notification2

      environment:
        SERVER_PORT: 8084

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: notification2

      depends_on:
        - kafka
        - eureka


    notification3:
      build: ../services/notification-service
      container_name: notification3

      environment:
        SERVER_PORT: 8084

        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
        EUREKA_INSTANCE_INSTANCE_ID: notification3

      depends_on:
        - kafka
        - eureka


  # ===========================================================
  # PERSISTENT VOLUMES
  # ===========================================================

  volumes:
    postgres-data:
